services:
  website:
    build: ./website
    volumes:
      - ./website:/app
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - VIRTUAL_HOST=website-mano.localhost,mano.test.fabrique.social.gouv.fr,mano.sesan.fr,preprod-mano.sesan.fr
      - PORT=8080
      - no_proxy=ad.sesan.fr,.gcsidf.local,localhost,127.0.0.1
      - https_proxy=http://sesclaprx-vip.grita.fr:3128
      - http_proxy=http://sesclaprx-vip.grita.fr:3128

  dashboard:
    build:
      context: ./dashboard
      args:
        REACT_APP_SCHEME: ${REACT_APP_SCHEME}
        REACT_APP_HOST: ${REACT_APP_HOST}
        REACT_APP_USE_HTTP: ${REACT_APP_USE_HTTP}
    volumes:
      - ./dashboard:/app
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=espace-mano.localhost,espace-mano.test.fabrique.social.gouv.fr,espace-mano.sesan.fr,preprod-espace-mano.sesan.fr
      - PORT=8083
      - REACT_APP_SCHEME=${REACT_APP_SCHEME}
      - REACT_APP_HOST=${REACT_APP_HOST}
      - REACT_APP_USE_HTTP=${REACT_APP_USE_HTTP}
      - no_proxy=ad.sesan.fr,.gcsidf.local,localhost,127.0.0.1
      - https_proxy=http://sesclaprx-vip.grita.fr:3128
      - http_proxy=http://sesclaprx-vip.grita.fr:3128

  api:
    build: ./api
    volumes:
      - ./api:/app
      # TODO: add link to storage
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: api-mano.localhost,api-mano.test.fabrique.social.gouv.fr,api-mano.sesan.fr,preprod-api-mano.sesan.fr
      PORT: 3000
      DEPLOY_KEY_FILE: /run/secrets/deploy_key
      PGHOST: host.docker.internal
      PGUSER_FILE: /run/secrets/pguser
      PGPASSWORD_FILE: /run/secrets/pgpassword
      PGDATABASE_FILE: /run/secrets/database
      STORAGE_DIRECTORY: /app/storage
      SECRET: /run/secrets/secret
      no_proxy: ad.sesan.fr,.gcsidf.local,localhost,127.0.0.1
      https_proxy: http://sesclaprx-vip.grita.fr:3128
      http_proxy: http://sesclaprx-vip.grita.fr:3128
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - deploy_key
      - pgpassword
      - pguser
      - secret
      - database

  metabase:
    image: metabase/metabase
    environment:
      - VIRTUAL_HOST=metabase-mano.localhost,metabase-mano.test.fabrique.social.gouv.fr,metabase-mano.sesan.fr,preprod-metabase-mano.sesan.fr
    volumes:
      - ./metabase:/metabase-data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

secrets:
  deploy_key:
    file: ./.secrets/deploy_key
  pgpassword:
    file: ./.secrets/pgpassword
  pguser:
    file: ./.secrets/pguser
  secret:
    file: ./.secrets/secret
  database:
    file: ./.secrets/database
