services:
  website:
    restart: always
    build: ./website
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - VIRTUAL_HOST=website-mano.localhost,mano.test.fabrique.social.gouv.fr,mano.sesan.fr,preprod-mano.sesan.fr
      - PORT=8080
      - no_proxy=ad.sesan.fr,.gcsidf.local,localhost,127.0.0.1
      - https_proxy=http://sesclaprx-vip.grita.fr:3128
      - http_proxy=http://sesclaprx-vip.grita.fr:3128

  dashboard:
    restart: always
    build:
      context: ./dashboard
      args:
        VITE_SCHEME: ${VITE_SCHEME}
        VITE_HOST: ${VITE_HOST}
        VITE_USE_HTTP: ${VITE_USE_HTTP}
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=espace-mano.localhost,espace-mano.test.fabrique.social.gouv.fr,espace-mano.sesan.fr,preprod-espace-mano.sesan.fr
      - PORT=8083
      - VITE_SCHEME=${VITE_SCHEME}
      - VITE_HOST=${VITE_HOST}
      - VITE_USE_HTTP=${VITE_USE_HTTP}
      - no_proxy=ad.sesan.fr,.gcsidf.local,localhost,127.0.0.1
      - https_proxy=http://sesclaprx-vip.grita.fr:3128
      - http_proxy=http://sesclaprx-vip.grita.fr:3128

  api:
    restart: always
    build: ./api
    volumes:
      # Storage
      - /var/data:/data
      - /var/deploy:/deploy
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: api-mano.localhost,api-mano.test.fabrique.social.gouv.fr,api-mano.sesan.fr,preprod-api-mano.sesan.fr
      PORT: 3000
      DEPLOY_KEY_FILE: /run/secrets/deploy_key
      PGHOST: host.docker.internal
      PGUSER_FILE: /run/secrets/pguser
      PGPASSWORD_FILE: /run/secrets/pgpassword
      PGDATABASE_FILE: /run/secrets/database
      STORAGE_DIRECTORY: /data
      SECRET: /run/secrets/secret
      MANO_API_IS_PRODUCTION: "true"
      no_proxy: ad.sesan.fr,.gcsidf.local,localhost,127.0.0.1
      https_proxy: http://sesclaprx-vip.grita.fr:3128
      http_proxy: http://sesclaprx-vip.grita.fr:3128
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - deploy_key
      - pgpassword
      - pguser
      - secret
      - database
  metabase:
    restart: always
    image: metabase/metabase
    environment:
      VIRTUAL_HOST: metabase-mano.localhost,metabase-mano.test.fabrique.social.gouv.fr,metabase-mano.sesan.fr,preprod-metabase-mano.sesan.fr
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER_FILE: /run/secrets/mb_db_user
      MB_DB_PASS_FILE: /run/secrets/mb_db_password
      MB_DB_HOST: host.docker.internal
    volumes:
      - ./metabase:/metabase-data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - mb_db_user
      - mb_db_password

  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./.server/vhost:/etc/nginx/vhost.d

secrets:
  deploy_key:
    file: ./.secrets/deploy_key
  pgpassword:
    file: ./.secrets/pgpassword
  pguser:
    file: ./.secrets/pguser
  secret:
    file: ./.secrets/secret
  database:
    file: ./.secrets/database
  mb_db_user:
    file: ./.secrets/mb_db_user
  mb_db_password:
    file: ./.secrets/mb_db_password
